// Code generated by Begonia. DO NOT EDIT.
// versions:
// 	Begonia v1.0.2
// source: serve\user.go
// begonia server file

package serve

import (
	"context"
	"errors"
	"github.com/MashiroC/begonia/app"
	"github.com/MashiroC/begonia/app/coding"
	cRegister "github.com/MashiroC/begonia/core/register"
)

var (
	_RPCUserServerFuncList []cRegister.FunInfo

	_RPCUserServerLoginInSchema = `
{
			"namespace":"begonia.func.Login",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"F1","type":"string","alias":"name"}
,{"name":"F2","type":"string","alias":"password"}

			]
		}`
	_RPCUserServerLoginOutSchema = `
{
			"namespace":"begonia.func.Login",
			"type":"record",
			"name":"Out",
			"fields":[
				{"name":"F1","type":"int","alias":"code"}
,{"name":"F2","type":"string","alias":"message"}
,{"name":"F3","type":"string","alias":"data"}

			]
		}`
	_RPCUserServerLoginInCoder  coding.Coder
	_RPCUserServerLoginOutCoder coding.Coder

	_RPCUserServerRegisterInSchema = `
{
			"namespace":"begonia.func.Register",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"F1","type":"string","alias":"name"}
,{"name":"F2","type":"string","alias":"password"}
,{"name":"F3","type":"string","alias":"email"}
,{"name":"F4","type":"long","alias":"telephone"}

			]
		}`
	_RPCUserServerRegisterOutSchema = `
{
			"namespace":"begonia.func.Register",
			"type":"record",
			"name":"Out",
			"fields":[
				{"name":"F1","type":"int","alias":"code"}
,{"name":"F2","type":"string","alias":"message"}

			]
		}`
	_RPCUserServerRegisterInCoder  coding.Coder
	_RPCUserServerRegisterOutCoder coding.Coder

	_RPCUserServerUpdateInSchema = `
{
			"namespace":"begonia.func.Update",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"F1","type":"int","alias":"userId"}
,{"name":"F2","type":"int","alias":"operateType"}
,{"name":"F3","type":"string","alias":"content"}

			]
		}`
	_RPCUserServerUpdateOutSchema = `
{
			"namespace":"begonia.func.Update",
			"type":"record",
			"name":"Out",
			"fields":[
				{"name":"F1","type":"int","alias":"code"}
,{"name":"F2","type":"string","alias":"message"}

			]
		}`
	_RPCUserServerUpdateInCoder  coding.Coder
	_RPCUserServerUpdateOutCoder coding.Coder
)

type _RPCUserServerLoginIn struct {
	F1 string
	F2 string
}

type _RPCUserServerLoginOut struct {
	F1 int
	F2 string
	F3 string
}

type _RPCUserServerRegisterIn struct {
	F1 string
	F2 string
	F3 string
	F4 int64
}

type _RPCUserServerRegisterOut struct {
	F1 int
	F2 string
}

type _RPCUserServerUpdateIn struct {
	F1 int
	F2 int
	F3 string
}

type _RPCUserServerUpdateOut struct {
	F1 int
	F2 string
}

func init() {
	app.ServiceAppMode = app.Ast

	var err error

	_RPCUserServerLoginInCoder, err = coding.NewAvro(_RPCUserServerLoginInSchema)
	if err != nil {
		panic(err)
	}
	_RPCUserServerLoginOutCoder, err = coding.NewAvro(_RPCUserServerLoginOutSchema)
	if err != nil {
		panic(err)
	}

	_RPCUserServerRegisterInCoder, err = coding.NewAvro(_RPCUserServerRegisterInSchema)
	if err != nil {
		panic(err)
	}
	_RPCUserServerRegisterOutCoder, err = coding.NewAvro(_RPCUserServerRegisterOutSchema)
	if err != nil {
		panic(err)
	}

	_RPCUserServerUpdateInCoder, err = coding.NewAvro(_RPCUserServerUpdateInSchema)
	if err != nil {
		panic(err)
	}
	_RPCUserServerUpdateOutCoder, err = coding.NewAvro(_RPCUserServerUpdateOutSchema)
	if err != nil {
		panic(err)
	}

	_RPCUserServerFuncList = []cRegister.FunInfo{

		{
			Name:      "Login",
			InSchema:  _RPCUserServerLoginInSchema,
			OutSchema: _RPCUserServerLoginOutSchema},

		{
			Name:      "Register",
			InSchema:  _RPCUserServerRegisterInSchema,
			OutSchema: _RPCUserServerRegisterOutSchema},

		{
			Name:      "Update",
			InSchema:  _RPCUserServerUpdateInSchema,
			OutSchema: _RPCUserServerUpdateOutSchema},
	}
}

func (d *RPCUserServer) Do(ctx context.Context, fun string, param []byte) (result []byte, err error) {
	switch fun {

	case "Login":
		var in _RPCUserServerLoginIn
		err = _RPCUserServerLoginInCoder.DecodeIn(param, &in)
		if err != nil {
			panic(err)
		}

		res1, res2, res3 := d.Login(

			in.F1, in.F2,
		)
		if err != nil {
			return nil, err
		}
		var out _RPCUserServerLoginOut
		out.F1 = res1
		out.F2 = res2
		out.F3 = res3

		res, err := _RPCUserServerLoginOutCoder.Encode(out)
		if err != nil {
			panic(err)
		}
		return res, nil

	case "Register":
		var in _RPCUserServerRegisterIn
		err = _RPCUserServerRegisterInCoder.DecodeIn(param, &in)
		if err != nil {
			panic(err)
		}

		res1, res2 := d.Register(

			in.F1, in.F2, in.F3, in.F4,
		)
		if err != nil {
			return nil, err
		}
		var out _RPCUserServerRegisterOut
		out.F1 = res1
		out.F2 = res2

		res, err := _RPCUserServerRegisterOutCoder.Encode(out)
		if err != nil {
			panic(err)
		}
		return res, nil

	case "Update":
		var in _RPCUserServerUpdateIn
		err = _RPCUserServerUpdateInCoder.DecodeIn(param, &in)
		if err != nil {
			panic(err)
		}

		res1, res2 := d.Update(

			in.F1, in.F2, in.F3,
		)
		if err != nil {
			return nil, err
		}
		var out _RPCUserServerUpdateOut
		out.F1 = res1
		out.F2 = res2

		res, err := _RPCUserServerUpdateOutCoder.Encode(out)
		if err != nil {
			panic(err)
		}
		return res, nil

	default:
		err = errors.New("rpc usersCentercall error: fun not exist")
	}
	return
}

func (d *RPCUserServer) FuncList() []cRegister.FunInfo {
	return _RPCUserServerFuncList
}
