// Code generated by Begonia. DO NOT EDIT.
// versions:
// 	Begonia v1.0.2
// begonia base client file

package usersCentercall

import (
	"github.com/MashiroC/begonia"
)

var BegoniaCli begonia.Client = begonia.NewClientWithAst()
