// Code generated by Begonia. DO NOT EDIT.
// versions:
// 	Begonia v1.0.2
// source: serve\routers.go
// begonia client file

package usersCentercall

import (
	"github.com/MashiroC/begonia/app"
	appClient "github.com/MashiroC/begonia/app/client"
	"github.com/MashiroC/begonia/app/coding"
)

var (
	RPCUserServerService appClient.Service

	_RPCUserServerServiceLogin appClient.RemoteFunSync

	_RPCUserServerServiceLoginInSchema = `
{
			"namespace":"begonia.func.Login",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"F1","type":"string","alias":"name"}
,{"name":"F2","type":"string","alias":"password"}

			]
		}`
	_RPCUserServerServiceLoginOutSchema = `
{
			"namespace":"begonia.func.Login",
			"type":"record",
			"name":"Out",
			"fields":[
				{"name":"F1","type":"int","alias":"code"}
,{"name":"F2","type":"string","alias":"message"}

			]
		}`
	_RPCUserServerServiceLoginInCoder  coding.Coder
	_RPCUserServerServiceLoginOutCoder coding.Coder

	_RPCUserServerServiceRegister appClient.RemoteFunSync

	_RPCUserServerServiceRegisterInSchema = `
{
			"namespace":"begonia.func.Register",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"F1","type":"string","alias":"name"}
,{"name":"F2","type":"string","alias":"password"}
,{"name":"F3","type":"string","alias":"email"}
,{"name":"F4","type":"long","alias":"telephone"}

			]
		}`
	_RPCUserServerServiceRegisterOutSchema = `
{
			"namespace":"begonia.func.Register",
			"type":"record",
			"name":"Out",
			"fields":[
				{"name":"F1","type":"int","alias":"code"}
,{"name":"F2","type":"string","alias":"message"}

			]
		}`
	_RPCUserServerServiceRegisterInCoder  coding.Coder
	_RPCUserServerServiceRegisterOutCoder coding.Coder

	_RPCUserServerServiceUpdate appClient.RemoteFunSync

	_RPCUserServerServiceUpdateInSchema = `
{
			"namespace":"begonia.func.Update",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"F1","type":"int","alias":"userId"}
,{"name":"F2","type":"int","alias":"operateType"}
,{"name":"F3","type":"string","alias":"content"}

			]
		}`
	_RPCUserServerServiceUpdateOutSchema = `
{
			"namespace":"begonia.func.Update",
			"type":"record",
			"name":"Out",
			"fields":[
				{"name":"F1","type":"int","alias":"code"}
,{"name":"F2","type":"string","alias":"message"}

			]
		}`
	_RPCUserServerServiceUpdateInCoder  coding.Coder
	_RPCUserServerServiceUpdateOutCoder coding.Coder
)

type _RPCUserServerServiceLoginIn struct {
	F1 string
	F2 string
}

type _RPCUserServerServiceLoginOut struct {
	F1 int
	F2 string
}

type _RPCUserServerServiceRegisterIn struct {
	F1 string
	F2 string
	F3 string
	F4 int64
}

type _RPCUserServerServiceRegisterOut struct {
	F1 int
	F2 string
}

type _RPCUserServerServiceUpdateIn struct {
	F1 int
	F2 int
	F3 string
}

type _RPCUserServerServiceUpdateOut struct {
	F1 int
	F2 string
}

func init() {
	app.ServiceAppMode = app.Ast

	bService, err := BegoniaCli.Service("UsersServer")
	if err != nil {
		panic(err)
	}

	_RPCUserServerServiceLogin, err = bService.FuncSync("Login")

	_RPCUserServerServiceLoginInCoder, err = coding.NewAvro(_RPCUserServerServiceLoginInSchema)
	if err != nil {
		panic(err)
	}
	_RPCUserServerServiceLoginOutCoder, err = coding.NewAvro(_RPCUserServerServiceLoginOutSchema)
	if err != nil {
		panic(err)
	}

	_RPCUserServerServiceRegister, err = bService.FuncSync("Register")

	_RPCUserServerServiceRegisterInCoder, err = coding.NewAvro(_RPCUserServerServiceRegisterInSchema)
	if err != nil {
		panic(err)
	}
	_RPCUserServerServiceRegisterOutCoder, err = coding.NewAvro(_RPCUserServerServiceRegisterOutSchema)
	if err != nil {
		panic(err)
	}

	_RPCUserServerServiceUpdate, err = bService.FuncSync("Update")

	_RPCUserServerServiceUpdateInCoder, err = coding.NewAvro(_RPCUserServerServiceUpdateInSchema)
	if err != nil {
		panic(err)
	}
	_RPCUserServerServiceUpdateOutCoder, err = coding.NewAvro(_RPCUserServerServiceUpdateOutSchema)
	if err != nil {
		panic(err)
	}

}

func Login(name string, password string) (code int, message string, err error) {
	var in _RPCUserServerServiceLoginIn
	in.F1 = name
	in.F2 = password

	b, err := _RPCUserServerServiceLoginInCoder.Encode(in)
	if err != nil {
		panic(err)
	}

	begoniaResTmp, err := _RPCUserServerServiceLogin(b)
	if err != nil {
		return
	}

	var out _RPCUserServerServiceLoginOut
	err = _RPCUserServerServiceLoginOutCoder.DecodeIn(begoniaResTmp.([]byte), &out)
	if err != nil {
		panic(err)
	}

	code = out.F1

	message = out.F2

	return
}

func Register(name string, password string, email string, telephone int64) (code int, message string, err error) {
	var in _RPCUserServerServiceRegisterIn
	in.F1 = name
	in.F2 = password
	in.F3 = email
	in.F4 = telephone

	b, err := _RPCUserServerServiceRegisterInCoder.Encode(in)
	if err != nil {
		panic(err)
	}

	begoniaResTmp, err := _RPCUserServerServiceRegister(b)
	if err != nil {
		return
	}

	var out _RPCUserServerServiceRegisterOut
	err = _RPCUserServerServiceRegisterOutCoder.DecodeIn(begoniaResTmp.([]byte), &out)
	if err != nil {
		panic(err)
	}

	code = out.F1

	message = out.F2

	return
}

func Update(userId int, operateType int, content string) (code int, message string, err error) {
	var in _RPCUserServerServiceUpdateIn
	in.F1 = userId
	in.F2 = operateType
	in.F3 = content

	b, err := _RPCUserServerServiceUpdateInCoder.Encode(in)
	if err != nil {
		panic(err)
	}

	begoniaResTmp, err := _RPCUserServerServiceUpdate(b)
	if err != nil {
		return
	}

	var out _RPCUserServerServiceUpdateOut
	err = _RPCUserServerServiceUpdateOutCoder.DecodeIn(begoniaResTmp.([]byte), &out)
	if err != nil {
		panic(err)
	}

	code = out.F1

	message = out.F2

	return
}
